# Generated by Django 4.2.29 on 2026-03-15 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(default='')),
                ('symptom_hash', models.CharField(blank=True, default='', max_length=64)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('advice', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('nepali_advice', models.TextField(blank=True, default='')),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('brief_advice', models.TextField(blank=True, default='')),
                ('detailed_advice', models.TextField(blank=True, default='')),
                ('food_eat', models.TextField(blank=True, default='')),
                ('food_avoid', models.TextField(blank=True, default='')),
                ('dos', models.TextField(blank=True, default='')),
                ('donts', models.TextField(blank=True, default='')),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
